# Generated by Django 3.0.6 on 2021-10-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squid_engine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code_rule',
            old_name='XPath_Comparator',
            new_name='Comparator',
        ),
        migrations.RenameField(
            model_name='code_rule',
            old_name='XPath_Condition',
            new_name='Condition',
        ),
        migrations.RenameField(
            model_name='code_rule',
            old_name='XPath_Expected_Value',
            new_name='Expected_Value',
        ),
        migrations.RenameField(
            model_name='folder_structure_rule',
            old_name='Folder_Structure_Comparator',
            new_name='Comparator',
        ),
        migrations.RenameField(
            model_name='folder_structure_rule',
            old_name='Folder_Structure_Condition',
            new_name='Condition',
        ),
        migrations.RenameField(
            model_name='folder_structure_rule',
            old_name='Folder_Structure_Expected_Value',
            new_name='Expected_Value',
        ),
        migrations.RenameField(
            model_name='platform_rule',
            old_name='Platform_Comparator',
            new_name='Comparator',
        ),
        migrations.RenameField(
            model_name='platform_rule',
            old_name='Platform_Condition',
            new_name='Condition',
        ),
        migrations.RenameField(
            model_name='platform_rule',
            old_name='Platform_Expected_Value',
            new_name='Expected_Value',
        ),
        migrations.RenameField(
            model_name='raml_rule',
            old_name='Raml_Comparator',
            new_name='Comparator',
        ),
        migrations.RenameField(
            model_name='raml_rule',
            old_name='Raml_Condition',
            new_name='Condition',
        ),
        migrations.RenameField(
            model_name='raml_rule',
            old_name='Raml_Expected_Value',
            new_name='Expected_Value',
        ),
        migrations.RenameField(
            model_name='security_rule',
            old_name='Security_Comparator',
            new_name='Comparator',
        ),
        migrations.RenameField(
            model_name='security_rule',
            old_name='Security_Condition',
            new_name='Condition',
        ),
        migrations.RenameField(
            model_name='security_rule',
            old_name='Security_Expected_Value',
            new_name='Expected_Value',
        ),
    ]
